"""empty message

Revision ID: 088a351f34cf
Revises: ede2a67a29aa
Create Date: 2020-02-19 14:38:11.666382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '088a351f34cf'
down_revision = 'ede2a67a29aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('user_product_view')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_product_view',
    sa.Column('up_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('productId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('orderId', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('orders',
    sa.Column('o_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('totalPrice', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date_of_purchase', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('o_id', 'totalPrice', name='orders_pkey')
    )
    # ### end Alembic commands ###
