"""empty message

Revision ID: 1bbd5fbf9125
Revises: 46b52514eca3
Create Date: 2020-02-19 14:39:23.070684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bbd5fbf9125'
down_revision = '46b52514eca3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_product_view',
    sa.Column('up_id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('productId', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('o_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['o_id'], ['orders.o_id'], ),
    sa.ForeignKeyConstraint(['productId'], ['products.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('up_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_product_view')
    # ### end Alembic commands ###
