"""empty message

Revision ID: 2a73cdac7009
Revises: 33604c206ea4
Create Date: 2020-02-18 16:25:34.618015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a73cdac7009'
down_revision = '33604c206ea4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('e_id', sa.Integer(), nullable=False),
    sa.Column('e_name', sa.String(length=64), nullable=True),
    sa.Column('e_email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('e_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee')
    # ### end Alembic commands ###
