"""empty message

Revision ID: 2b9de3f9f9e8
Revises: 390a99023de6
Create Date: 2020-02-19 09:38:30.784064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b9de3f9f9e8'
down_revision = '390a99023de6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('SKU', sa.String(length=128), nullable=True),
    sa.Column('productName', sa.String(length=128), nullable=True),
    sa.Column('brand', sa.String(length=64), nullable=True),
    sa.Column('productDescription', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
