"""empty message

Revision ID: 3834c30729b1
Revises: 1bbd5fbf9125
Create Date: 2020-02-19 14:58:30.618813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3834c30729b1'
down_revision = '1bbd5fbf9125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('r_id', sa.Integer(), nullable=False),
    sa.Column('userProductId', sa.Integer(), nullable=False),
    sa.Column('productRating', sa.Integer(), nullable=True),
    sa.Column('reviewTitle', sa.String(length=64), nullable=True),
    sa.Column('reviewDetails', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['userProductId'], ['user_product_view.up_id'], ),
    sa.PrimaryKeyConstraint('r_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    # ### end Alembic commands ###
