"""empty message

Revision ID: 4632663bb2d4
Revises: 33fd688a2a45
Create Date: 2020-02-19 11:19:33.134190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4632663bb2d4'
down_revision = '33fd688a2a45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('date_of_purchase', sa.Date(), nullable=True, storage_format='%(month)02d/%(day)02d/%(year)04d'))
    op.drop_column('orders', 'purchaseDate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('purchaseDate', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('orders', 'date_of_purchase')
    # ### end Alembic commands ###
