"""empty message

Revision ID: 46b52514eca3
Revises: 088a351f34cf
Create Date: 2020-02-19 14:38:33.592788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46b52514eca3'
down_revision = '088a351f34cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('o_id', sa.Integer(), nullable=False),
    sa.Column('date_of_purchase', sa.Date(), nullable=True),
    sa.Column('totalPrice', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('o_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
