"""empty message

Revision ID: 56fca778756c
Revises: 2b9de3f9f9e8
Create Date: 2020-02-19 10:35:43.514931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56fca778756c'
down_revision = '2b9de3f9f9e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('o_id', sa.Integer(), nullable=False),
    sa.Column('purchaseDate', sa.DateTime(), nullable=True),
    sa.Column('totalPrice', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('o_id', 'totalPrice')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
