"""empty message

Revision ID: 79ba8a918b29
Revises: 540a66e0f9c1
Create Date: 2020-02-19 01:08:10.901551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79ba8a918b29'
down_revision = '540a66e0f9c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gender', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('lastname', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('phonenumber', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('registerationDate', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('state', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('zipcode', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'zipcode')
    op.drop_column('user', 'state')
    op.drop_column('user', 'registerationDate')
    op.drop_column('user', 'phonenumber')
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'gender')
    # ### end Alembic commands ###
