"""empty message

Revision ID: ede2a67a29aa
Revises: 4632663bb2d4
Create Date: 2020-02-19 11:54:38.430108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ede2a67a29aa'
down_revision = '4632663bb2d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_product_view',
    sa.Column('up_id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('productId', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('orderId', sa.Integer(), nullable=True),

    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'totalPrice',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('user_product_view')
    # ### end Alembic commands ###
